name: Check and buid addon

on:
  push:
    branches:
      - master
    tags:
      - '*'
    # paths-ignore:
    #- '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        #WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Rename WhatsNew.md
        if: github.ref_type == 'branch'
        run: |
           mv -vf WhatsNew.md WhatsNew_.md
           echo "file moved"

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -qo 011

      - name: Package retail
        if: ${{ !contains(github.event.head_commit.message, '#skipretail') }}
        uses: BigWigsMods/packager@master

      - name: Package classic
        if: ${{ !contains(github.event.head_commit.message, '#skipclassic') }}
        uses: BigWigsMods/packager@master
        with:
          args: -g classic

      - name: Package mists
        if: ${{ !contains(github.event.head_commit.message, '#skipmop') }}
        uses: BigWigsMods/packager@master
        with:
          args: -g mists

      - name: Package bcc
        if: ${{ !contains(github.event.head_commit.message, '#skipbcc') }}
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc
